# Basic frames
goal_frame_id: 'map'
odom_frame_id: 'odom'
base_frame_id: 'base_footprint'

# Not used any more
wait_duration:                0.0
waypoint_distance_tolerance:  0.0

# Topics subscribed/publishing to
go_to_next_waypoint_trigger_topic:  'go_to_next_waypoint_trigger'
rviz_waypoints_topic:               'rviz_waypoints'             # waypoints
rviz_waypoints_ready_topic:         'rviz_waypoints_ready' # path_ready
file_waypoints_ready_topic:         'file_waypoints_ready' # start_journey
waypoints_reset_topic:              'waypoints_reset'
waypoints_visualisation_topic:      'waypoints_2'  # waypoints_2
